// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html
//       lang="en"
//       className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
//     >
//       <body className="min-h-full flex flex-col">{children}</body>
//     </html>
//   );
// }


// export const metadata = {
//   title: "SavoryBite",
//   description: "Premium restaurant ordering experience",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body>{children}</body>
//     </html>
//   );
// }


// import "./globals.css";

// export const metadata = {
//   title: "Gracee Ville Kitchen N Events",
//   description: "Premium catering, kitchen and events experience",
// };

// // export const metadata = {
// //   title: "SavoryBite",
// //   description: "Premium restaurant ordering experience",
// // };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <head>
//         <link rel="manifest" href="/manifest.json" />
//         <meta name="theme-color" content="#f97316" />
//       </head>
//       <body>{children}</body>
//     </html>
//   );
// }


// import "./globals.css";

// export const metadata = {
//   title: "Gracee Ville Kitchen N Events",
//   description: "Premium catering, kitchen and events experience",
//   manifest: "/manifest.json",
//   themeColor: "#f97316",
//   appleWebApp: {
//     capable: true,
//     statusBarStyle: "default",
//     title: "Gracee Ville",
//   },
//   icons: {
//     icon: [
//       { url: "/icons/icon-192.png", sizes: "192x192", type: "image/png" },
//       { url: "/icons/icon-512.png", sizes: "512x512", type: "image/png" },
//     ],
//     apple: [
//       { url: "/icons/icon-192.png", sizes: "192x192", type: "image/png" },
//     ],
//   },
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body>{children}</body>
//     </html>
//   );
// }

import "./globals.css";

export const metadata = {
  title: "Gracee Ville Kitchen N Events",
  description: "Premium catering, kitchen and events experience",
  manifest: "/manifest.json",
  appleWebApp: {
    capable: true,
    statusBarStyle: "default",
    title: "Gracee Ville",
  },
  icons: {
    icon: [
      { url: "/icons/icon-192.png", sizes: "192x192", type: "image/png" },
      { url: "/icons/icon-512.png", sizes: "512x512", type: "image/png" },
    ],
    apple: [
      { url: "/icons/icon-192.png", sizes: "192x192", type: "image/png" },
    ],
  },
};

export const viewport = {
  themeColor: "#f97316",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}